---
kind: pipeline
type: kubernetes
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: admin
    password: admin
    registry: 103.153.255.227:5000
    repo: 103.153.255.227:5000/webapp
    dockerfile: ./svc1/Dockerfile
    insecure: true
- name: deliver
  image: 103.153.255.227:5000/drone-kubectl
  settings:
   kubernetes_server:
      from_secret: k8s_server
   kubernetes_cert:
      from_secret: k8s_cert
   kubernetes_token:
      from_secret: k8s_token
  commands:
  - kubectl rollout restart deployment/nginx-deployment -n default
